name: Hugging phase demo

on:
# allow push on  ain branch
   push:
    branches: [main]
    # alow pull on main braint
   pull_request:
      branches: [main]
  #Allow to run workflow manually 
   workflow_dispatch:    
   #sequencial run of the work as job
jobs:

  sync-on-hub:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Add remote
        env:git-actions
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.15
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.15
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
    
    
