name: Hugging phase demo

on:
# allow push on  ain branch
   push:
    branches: [main]
    # alow pull on the main braint
   pull_request:
      branches: [main]
  #Allow to run workflow manually 
   workflow_dispatch:    
   #sequencial run of the work as job
jobs:

  sync-on-hub:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         with:
          fetch-depth: 0
       - name: Add remote
         env:
           HF: ${{secrets.HUGGING_FACE_ACT_SECRET}}
         run: git remote add space https://agbenge:$HF@huggingface.co/spaces/agbenge/demo
       - name: Push to hub
         env:
           HF: ${{secrets.HUGGING_FACE_ACT_SECRET}}
         run: git push --force https://agbenge:$HF@huggingface.co/spaces/agbenge/demo main
 
    
    
